name: sst-rdex
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - img2pdf=0.6.1
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libdeflate=1.24
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libtiff=4.7.1
  - libuuid=2.41.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openjpeg=2.5.4
  - openssl=3.5.4
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - python=3.10.0
  - python_abi=3.10
  - readline=8.2
  - setuptools=80.9.0
  - sqlite=3.50.4
  - tk=8.6.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstd=1.5.7
  - pip:
      - abcd-tools==0.0.1
      - attrs==25.3.0
      - bayesian-optimization==1.5.0
      - bp-neurotools==0.24
      - brain-pred-toolbox==2.3.2
      - certifi==2025.8.3
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - cma==4.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - distlib==0.4.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.59.2
      - identify==2.6.14
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - loky==3.5.6
      - lxml==6.0.2
      - matplotlib==3.5.3
      - nbformat==5.10.4
      - nbstripout==0.8.1
      - networkx==3.4.2
      - nevergrad==0.5.0
      - nibabel==5.3.2
      - nilearn==0.12.1
      - nodeenv==1.9.1
      - numpy==1.23.5
      - packaging==25.0
      - pandas==1.5.0
      - patsy==1.0.1
      - pre-commit==4.3.0
      - pyaml==25.7.0
      - pyarrow==21.0.0
      - pyparsing==3.2.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - scikit-image==0.24.0
      - scikit-learn==1.1.3
      - scipy==1.15.3
      - seaborn==0.12.0
      - six==1.17.0
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - virtualenv==20.34.0
